### ISSUE TITLE
Bug: Some complex JSON cannot be parsed

### ISSUE THREAD

**Issue by BigHeadDev** [arnav-kr/json-formatter#24]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

[a complex json](https://www.kuaiyun-api.com/api.php/provide/vod/kuaiyunbo?ac=detail)

You can try this URL~~~

### System Info

```markdown
- OS:
- Browser:
```

**Comment by arnav-kr** [comment]
can you provide another working url? this one seems to be down

**Comment by BigHeadDev** [comment]
> can you provide another working url? this one seems to be down
https://[cj.lziapi.com/api.php/provide/vod/from/lzm3u8?ac=detail&ids=79752](https://cj.lziapi.com/api.php/provide/vod/from/lzm3u8?ac=detail&ids=79752)

**Comment by arnav-kr** [comment]
Hi, thanks for providing the new URL,
I checked it
and found, it is the issue with the API provider,
the response that they give contains a property `vod-content` which contains valid HTML content,
and they are setting the `content-type` as `text/html` in the response, so when the browser (not the extension) gets the response, it tries to render that valid HTML, and thus breaking the valid JSON structure
and as JSON Formatter can only get content from the page's HTML, it sees the same that browser sees, and ignore formatting due to invalid JSON.

![JSON being rendered partially as HTML][ref1]

Fixes:
---
+ if you are the creator of the API, just set `content-type: application/json` in response headers, and the browser will see it as JSON and will not try to render the HTML part, and JSON Formatter should work fine in that case.
+ If you are the consumer, best you can do is reporting them, as even without JSON Formatter, if you copy the response displayed in the browser, it'd be corrupt JSON

[ref1]: https://github.com/arnav-kr/json-formatter/assets/72879799/49e7add9-a85f-466f-9b3d-9c9cb3511c78 "JSON being rendered partially as HTML"

**Comment by BigHeadDev** [comment]
> Hi, thanks for providing the new URL, I checked it and found, it is the issue with the API provider, the response that they give contains a property which contains valid HTML content, and they are setting the as in the response, so when the browser (not the extension) gets the response, it tries to render that valid HTML, and thus breaking the valid JSON structure and as JSON Formatter can only get content from the page's HTML, it sees the same that browser sees, and ignore formatting due to invalid JSON.`vod-content``content-type``text/html`
> 
> ![JSON being rendered partially as HTML](https://private-user-images.githubusercontent.com/72879799/343738965-49e7add9-a85f-466f-9b3d-9c9cb3511c78.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk1NDA0MDcsIm5iZiI6MTcxOTU0MDEwNywicGF0aCI6Ii83Mjg3OTc5OS8zNDM3Mzg5NjUtNDllN2FkZDktYTg1Zi00NjZmLTliM2QtOWM5Y2IzNTExYzc4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI4VDAyMDE0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJkNTRhYmY5OWYzYzBmZTIzZjI4MTNjZGYwNmMxNTc3N2UxNmFiNDQ3NTczYmI4NDBjMTI4ODk2NDRjNDY1ODEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.O2wMdizjlXS_VLQD41kaOdk8mnfq9L541bqA5ldtBeQ)
> 
> ## Fixes:
> * if you are the creator of the API, just set  in response headers, and the browser will see it as JSON and will not try to render the HTML part, and JSON Formatter should work fine in that case.`content-type: application/json`
> * If you are the consumer, best you can do is reporting them, as even without JSON Formatter, if you copy the response displayed in the browser, it'd be corrupt JSON

ok thanks for your replying~~
