### ISSUE TITLE
Bug: unicode decode

### ISSUE THREAD

**Issue by Zzzenk** [arnav-kr/json-formatter#32]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Can't decode Unicode to UTF.
Example: "\u041e\u0442\u043c\u0435\u043d\u0435\u043d"

### Expected Behavior

"\u041e\u0442\u043c\u0435\u043d\u0435\u043d"
should be displayed as
"Отменен"

### System Info

```markdown
- OS: Mac OS Sequoia
- Browser: Chrome
```

**Comment by arnav-kr** [comment]
Hi, Thanks for reporting, actually it wasn't a bug it was kind of feature, considering wysiwyg
still, I've now added a settings option that allows user to change this behaviour (default being it will convert unicode escape sequences to their respective characters)

The updates will take some time to reflect on the extension store due to review process, I'll notify once it's live

![image](https://github.com/user-attachments/assets/0b92a7b1-3a3e-4577-9916-e025afde424d)

**Comment by Zzzenk** [comment]
Thanks

**Comment by arnav-kr** [comment]
hey, it's live on webstore, forgot to tell

**Comment by Zzzenk** [comment]
Thx :) It wrks fine now
